### ISSUE TITLE
Använda ArrayList istället för Vector

### ISSUE THREAD

**Issue by artog** [Monaden/automatabuilder#14]

**Comment by artog** [comment]
Map<String,State> istället för List för states i DFA-klassen? Så kan man söka, typ `states.get("q0")`.

Nackdelen blir att iteration blir lite krångligare

```
for (Map.Entry<String, State> entry: states.entrySet()) {
    String name = entry.getKey();
    State q = entry.getValue();
}
```

**Comment by Oliv95** [comment]
Fördelen med en Map är väl att den har snabare lookup men förutom det är väll den bara sämre. Så frågan är väl hur ofta man kommer behöver göra en lookup.

**Comment by artog** [comment]
#18
