### ISSUE TITLE
power method return value

### ISSUE THREAD

**Issue by Oliv95** [Monaden/automatabuilder#17]
Borde nog retunera en collection

**Comment by artog** [comment]
Tror jag fixade det när jag gjorde vector -> list

Edit: Nästan rätt, gjorde ändringen när jag gjorde unit tests till alphabet. 
Se: https://github.com/Monaden/automatabuilder/commit/ea116cb43e10a4706c43ceacfc09b40778dd8c50#diff-676c2058fe9ad20ca484cfb88003b0e7
